export const homePageFeatured = [
  {
    imgUrl: "/images/starbucks-rewards.jpg",
    text: "Summer is brither with free treats.*",
    buttonText: "Join Starbucks® Rewards",
    bgColor: "var(--dark-green-color)",
    color: "white",
  },
  {
    imgUrl: "/images/cold-yellow-drinks.jpg",
    title: "Summer’s brightest new drinks",
    text: "Introducing the Pineapple Passionfruit Starbucks Refreshers® beverage and the Starbucks® Paradise Drink with creamy coconutmilk.",
    buttonText: "Learn more",
    bgColor: "var(--light-pink)",
    imgPosition: "right",
    color: "#1e3932",
  },
  {
    imgUrl: "/images/brew-two.jpg",
    title: "Cold brew for two",
    text: "Try the new Chocolate Cream Cold Brew with silky, chocolaty cold foam. Or go for a Vanilla Sweet Cream Cold Brew with house-made vanilla-flavored sweet cream.",
    buttonText: "Learn more",
    bgColor: "#f06464",
    color: "white",
  },
  {
    imgUrl: "/images/backpack-it.jpg",
    title: "Back-to-school smiles",
    text: "A Starbucks eGift makes an A+ treat for students, teachers and school support staff.",
    buttonText: "Send an eGift",
    bgColor: "#faaa5a",
    color: "#1e3932",
    imgPosition: "right",
  },
  {
    imgUrl: "/images/protein-bun.jpg",
    title: "Anytime protein",
    text: "The Impossible™ Breakfast Sandwich** will keep you going with a plant-based sausage patty, cage-free fried egg and Cheddar on a sesame ciabatta bun.",
    buttonText: "Order now",
    bgColor: "#9bf5b4",
    color: "#1e3932",
  },
];
